version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: svce_nginx
    ports:
      - "5002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - svce-app
    restart: always
    networks:
      - svce_network

  svce-app:
    build: .
    container_name: svce_app
    env_file:
      - .env.production
    volumes:
      # Keep uploads persistent
      - svce_uploads:/app/uploads
    depends_on:
      - svce-db
    restart: always
    networks:
      - svce_network

  svce-db:
    image: postgres:15
    container_name: svce_db_prod
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      PUBLIC_URL: http://103.176.195.216:5002
      POSTGRES_DB: svce_admissions
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Persist DB data
      - svce_pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - svce_network

volumes:
  svce_pgdata:
  svce_uploads:

networks:
  svce_network:
    driver: bridge
